### PR TITLE
fix: add lang validators in baseValidator

### LINKED ISSUE #65: Validators should check the validity of the language (lang) passed
[RunValidator](https://github.com/coding-blocks/judge-api/blob/72944d1764f56a6c06af7b1a46c90cfd16872e7d/src/routes/api/run/validators.ts#L14) and [SubmitValidator](https://github.com/coding-blocks/judge-api/blob/72944d1764f56a6c06af7b1a46c90cfd16872e7d/src/routes/api/submit/validators.ts#L14) both should  check if the `lang` is a correct language.

### PR DESCRIPTION
**Pull request by prabalsingh24**
fixes #65

### CODE REVIEW

**Comment by prabalsingh24** [comment]
@championswimmer  @jatinkatyal13 what do you think of this approach? Since `lang` is required in all the routes. I fetched it from DB in the start and stored in res.locals.langs.

**Comment by jatinkatyal13** [comment]
Fetching from DB is not a heavy operation given the number of rows will be very limited. Eager loading it means increased complexity and you would require a server restart if a new language is added

**Comment by prabalsingh24** [comment]
>  you would require a server restart if a new language is added

 `langs` are fetched everytime for each request. Just like API key of each request are verified. langs are also updated in `res.locals.langs` in each request

**Comment by jatinkatyal13** [comment]
We may or may not need langs in each request. E.g. polling

Performance improvements are not significant and in most cases worse with respect to the complexity introduced. Although a nice effort but closing this for now.

**Pull request closed without merging**
