### PR TITLE
fix: fix the condition for whitelist_domain api validator

### LINKED ISSUE #67: API validator whitelist domain Referer condition seems wrong
[this](https://github.com/coding-blocks/judge-api/blob/72944d1764f56a6c06af7b1a46c90cfd16872e7d/src/validators/ApiKeyValidators.ts#L22) seems wrong

### PR DESCRIPTION
**Pull request by prabalsingh24**
fixes #67

### CODE REVIEW

**Comment by championswimmer** [comment]
it is still wrong, we need to check if req.referrer matches it

**Comment by prabalsingh24** [comment]
> it is still wrong, we need to check if req.referrer matches it

Sorry, I did not know how this is working :P

**Comment by prabalsingh24** [comment]
@championswimmer have a look at this?

**Comment by jatinkatyal13** [comment]
LGTM! 🚀

**Pull request merged**
