### PR TITLE
fix: change stdin-->input and stdout-->output

### LINKED ISSUE #61: Replace Stdin-->input and Stdout-->output
In [task-master](https://github.com/coding-blocks/judge-taskmaster/blob/08503cf29c4d921880e9d91abe4bce8b31cd38e3/src/tasks/scenarios/submission.ts#L37), `testcases.input` is used whereas in [jude-api](https://github.com/coding-blocks/judge-api/blob/72944d1764f56a6c06af7b1a46c90cfd16872e7d/src/routes/api/submit/validators.ts#L35)  it is defined as `testcases[0].stdin` and `...stdout`

### PR DESCRIPTION
**Pull request by prabalsingh24**
fixes #61

### CODE REVIEW

**Comment by prabalsingh24** [comment]
I changed did it and it seems to be working too. Have a look at this whenever you're free :)


On a side note, i think it'd be better if we make it consistent. I mean for `run` scenario we're using `stdin` `stdout` whereas in `submit` scenario we're using `input` and `output`. (both in api and taskmaster)

@jatinkatyal13 your thoughts?

**Comment by jatinkatyal13** [comment]
These were the same concerns I was going through while working on it. Here are my thoughts

In the case of testcases input and output aren't base64 encoded data but the urls and hence didn'e went with stdin/stdout.

**Comment by prabalsingh24** [comment]
> In the case of testcases input and output aren't base64 encoded data but the urls and hence didn'e went with stdin/stdout.

Oh okayy,  makes sense this way :)

**Comment by prabalsingh24** [comment]
Also can you see this 'Referer' thing. and let me know if it's a bug. If yes. I'll open an issue and PR :)
https://github.com/coding-blocks/judge-api/pull/60#issuecomment-629137815
@jatinkatyal13

**Comment by prabalsingh24** [comment]
Can this be merged?

**Pull request merged**
